### ISSUE TITLE
Lack of code

### ISSUE THREAD

**Issue by B1Fr0st** [LeviCoder/test-2022#3]
Describe the issue: It's just a background 🖌️  do some work

Can you reproduce the issue consistenty: ✔️ Consistently, every time I open the page

Suggested edits: Make a great graphic/game

**Comment by LeviCoder** [comment]
lol I really should do something here. Didn't see this until I checked my email just now

**Comment by B1Fr0st** [comment]
dont worry, I have an open source requirement, so just start doing stuff and I'll add on

**Comment by LeviCoder** [comment]
cool. I'll think of something :smile:
